"""
LogiQ GitHub PR Module
Creates pull requests on GitHub with drafted patches for anomaly fixes.
Uses GitHub REST API v3.
"""

import os
import json
import base64
import requests
from datetime import datetime

from database.db import get_setting

GITHUB_API_BASE = 'https://api.github.com'


def get_github_config():
    """
    Retrieve GitHub configuration from environment or settings.

    Returns:
        dict: {'token': str, 'owner': str, 'repo': str} or None if not configured.
    """
    token = os.getenv('GITHUB_TOKEN') or get_setting('github_token')
    repo_str = os.getenv('GITHUB_REPO') or get_setting('github_repo') or ''

    if not token or not repo_str:
        return None

    parts = repo_str.strip().split('/')
    if len(parts) != 2:
        return None

    return {
        'token': token,
        'owner': parts[0],
        'repo': parts[1],
    }


def github_request(method, path, token, data=None):
    """
    Make an authenticated request to the GitHub API.

    Args:
        method (str): HTTP method ('GET', 'POST', 'PUT', 'PATCH').
        path (str): API path (e.g., '/repos/owner/repo/pulls').
        token (str): GitHub personal access token.
        data (dict): Request body data.

    Returns:
        tuple: (status_code, response_json)
    """
    headers = {
        'Authorization': f'Bearer {token}',
        'Accept': 'application/vnd.github.v3+json',
        'Content-Type': 'application/json',
    }

    url = f"{GITHUB_API_BASE}{path}"

    try:
        response = requests.request(
            method=method,
            url=url,
            headers=headers,
            json=data,
            timeout=15,
        )
        return response.status_code, response.json() if response.content else {}
    except Exception as e:
        return 500, {'message': str(e)}


def create_fix_pr(anomaly):
    """
    Create a GitHub pull request with a drafted patch for an anomaly fix.

    The PR includes:
    - A new file with the fix documentation/runbook
    - A descriptive title and body with the anomaly details

    Args:
        anomaly (dict): Anomaly data with id, message, category, level,
                        explanation, suggested_fix.

    Returns:
        dict: {'success': bool, 'message': str, 'pr_url': str or None}
    """
    config = get_github_config()
    if not config:
        return {
            'success': False,
            'message': 'GitHub integration not configured. Add your token and repo in Settings.',
            'pr_url': None,
        }

    token = config['token']
    owner = config['owner']
    repo = config['repo']
    anomaly_id = anomaly.get('id', 'unknown')
    category = anomaly.get('category', 'unknown').lower().replace(' ', '-')
    timestamp = datetime.now().strftime('%Y%m%d-%H%M%S')
    branch_name = f"logiq/fix-{category}-{anomaly_id}-{timestamp}"

    # Step 1: Get the default branch SHA
    status, repo_data = github_request('GET', f'/repos/{owner}/{repo}', token)
    if status != 200:
        return {'success': False, 'message': f'Failed to access repository: {repo_data.get("message", "")}', 'pr_url': None}

    default_branch = repo_data.get('default_branch', 'main')

    status, ref_data = github_request('GET', f'/repos/{owner}/{repo}/git/refs/heads/{default_branch}', token)
    if status != 200:
        return {'success': False, 'message': f'Failed to get branch ref: {ref_data.get("message", "")}', 'pr_url': None}

    base_sha = ref_data.get('object', {}).get('sha')

    # Step 2: Create the fix branch
    status, branch_data = github_request('POST', f'/repos/{owner}/{repo}/git/refs', token, {
        'ref': f'refs/heads/{branch_name}',
        'sha': base_sha,
    })
    if status not in (200, 201):
        return {'success': False, 'message': f'Failed to create branch: {branch_data.get("message", "")}', 'pr_url': None}

    # Step 3: Create the fix file
    fix_content = f"""# LogiQ Fix: {anomaly.get('category', 'Unknown')} — Anomaly #{anomaly_id}

**Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Severity**: {anomaly.get('level', 'error').upper()}
**Category**: {anomaly.get('category', 'Unknown')}

## Original Error

```
{anomaly.get('message', 'No message available')}
```

## Explanation

{anomaly.get('explanation', 'No explanation available')}

## Suggested Fix

{anomaly.get('suggested_fix', 'No fix available')}

---
*Generated by LogiQ — From chaos to clarity, in seconds.*
"""

    file_path = f"fixes/logiq-fix-{anomaly_id}-{timestamp}.md"
    encoded_content = base64.b64encode(fix_content.encode()).decode()

    status, file_data = github_request('PUT', f'/repos/{owner}/{repo}/contents/{file_path}', token, {
        'message': f'fix: LogiQ auto-fix for {anomaly.get("category", "unknown")} anomaly #{anomaly_id}',
        'content': encoded_content,
        'branch': branch_name,
    })
    if status not in (200, 201):
        return {'success': False, 'message': f'Failed to create fix file: {file_data.get("message", "")}', 'pr_url': None}

    # Step 4: Create the pull request
    pr_title = f"fix: [{anomaly.get('level', 'error').upper()}] {anomaly.get('category', 'Unknown')} — LogiQ Auto-Fix #{anomaly_id}"
    pr_body = f"""## LogiQ Automated Fix

**Anomaly ID**: #{anomaly_id}
**Severity**: {anomaly.get('level', 'error').upper()}
**Category**: {anomaly.get('category', 'Unknown')}

### Error Message
```
{anomaly.get('message', 'No message')[:500]}
```

### AI Explanation
{anomaly.get('explanation', 'No explanation available')}

### Suggested Fix
{anomaly.get('suggested_fix', 'No fix available')}

---
*This PR was automatically generated by [LogiQ](https://github.com/logiq) — From chaos to clarity, in seconds.*
"""

    status, pr_data = github_request('POST', f'/repos/{owner}/{repo}/pulls', token, {
        'title': pr_title,
        'body': pr_body,
        'head': branch_name,
        'base': default_branch,
    })

    if status in (200, 201):
        return {
            'success': True,
            'message': f'Pull request created successfully',
            'pr_url': pr_data.get('html_url', ''),
        }
    else:
        return {
            'success': False,
            'message': f'Failed to create PR: {pr_data.get("message", "")}',
            'pr_url': None,
        }
